name: CI/CD to EKS with Docker Hub

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1              # ✅ Change to your AWS region
  EKS_CLUSTER_NAME: my-eks-cluster    # ✅ Change to your cluster name
  DEPLOYMENT_NAME: my-eks-app
  NAMESPACE: default
  DOCKER_IMAGE: codersdiary/my-eks-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # 1️⃣ Login to Docker Hub
    - name: Docker Hub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 2️⃣ Build & Push Docker image
    - name: Build & Push Docker Image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        IMAGE_URI=${DOCKER_IMAGE}:${IMAGE_TAG}
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

        echo "🔨 Building Docker image..."
        docker build -t $IMAGE_URI .

        echo "📤 Pushing to Docker Hub..."
        docker push $IMAGE_URI

    # 3️⃣ Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # 4️⃣ Update kubeconfig for EKS
    - name: Update kubeconfig
      run: aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

    # 5️⃣ Apply manifests (first time only)
    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/

    # 6️⃣ Update Deployment image with new Docker Hub tag
    - name: Update Deployment image
      run: |
        kubectl set image deployment/${DEPLOYMENT_NAME} ${DEPLOYMENT_NAME}=$IMAGE_URI -n $NAMESPACE
        kubectl rollout status deployment/${DEPLOYMENT_NAME} -n $NAMESPACE
